const axios = require("axios");
const { cmd } = require("../command");
const config = require("../config");

cmd({
  pattern: "logo",
  alias: [
    "logo1", "logo2", "logo3", "logo4", "logo5", "logo6",
    "logo7", "logo8", "logo9", "logo10", "logo11", "logo12",
    "logo13", "logo14", "logo15", "logo16", "logo17", "logo18", "logo19"
  ],
  desc: "Generate custom logos using text",
  category: "tools",
  react: "🎨",
  filename: __filename
}, async (conn, msg, m) => {
  const prefix = config.PREFIX;
  const senderName = msg.pushName || "User";
  const commandName = m.command; // captures actual command e.g. logo5

  const logoUrls = {
    logo:  "https://api-pink-venom.vercel.app/api/logo?url=https://en.ephoto360.com/create-a-blackpink-style-logo-with-members-signatures-810.html&name=",
    logo1: "https://api-pink-venom.vercel.app/api/logo?url=https://en.ephoto360.com/online-blackpink-style-logo-maker-effect-711.html&name=",
    logo2: "https://api-pink-venom.vercel.app/api/logo?url=https://en.ephoto360.com/create-glossy-silver-3d-text-effect-online-802.html&name=",
    logo3: "https://api-pink-venom.vercel.app/api/logo?url=https://en.ephoto360.com/naruto-shippuden-logo-style-text-effect-online-808.html&name=",
    logo4: "https://api-pink-venom.vercel.app/api/logo?url=https://en.ephoto360.com/create-digital-glitch-text-effects-online-767.html&name=",
    logo5: "https://api-pink-venom.vercel.app/api/logo?url=https://en.ephoto360.com/create-pixel-glitch-text-effect-online-769.html&name=",
    logo6: "https://api-pink-venom.vercel.app/api/logo?url=https://en.ephoto360.com/create-online-3d-comic-style-text-effects-817.html&name=",
    logo7: "https://api-pink-venom.vercel.app/api/logo?url=https://en.ephoto360.com/create-colorful-neon-light-text-effects-online-797.html&name=",
    logo8: "https://api-pink-venom.vercel.app/api/logo?url=https://en.ephoto360.com/free-bear-logo-maker-online-673.html&name=",
    logo9: "https://api-pink-venom.vercel.app/api/logo?url=https://en.ephoto360.com/neon-devil-wings-text-effect-online-683.html&name=",
    logo10:"https://api-pink-venom.vercel.app/api/logo?url=https://en.ephoto360.com/write-text-on-wet-glass-online-589.html&name=",
    logo11:"https://api-pink-venom.vercel.app/api/logo?url=https://en.ephoto360.com/create-typography-status-online-with-impressive-leaves-357.html&name=",
    logo12:"https://api-pink-venom.vercel.app/api/logo?url=https://en.ephoto360.com/create-dragon-ball-style-text-effects-online-809.html&name=",
    logo13:"https://api-pink-venom.vercel.app/api/logo?url=https://en.ephoto360.com/handwritten-text-on-foggy-glass-online-680.html&name=",
    logo14:"https://api-pink-venom.vercel.app/api/logo?url=https://en.ephoto360.com/create-colorful-neon-light-text-effects-online-797.html&name=",
    logo15:"https://api-pink-venom.vercel.app/api/logo?url=https://en.ephoto360.com/create-a-3d-castle-pop-out-mobile-photo-effect-786.html&name=",
    logo16:"https://api-pink-venom.vercel.app/api/logo?url=https://en.ephoto360.com/create-a-frozen-christmas-text-effect-online-792.html&name=",
    logo17:"https://api-pink-venom.vercel.app/api/logo?url=https://en.ephoto360.com/beautiful-3d-foil-balloon-effects-for-holidays-and-birthday-803.html&name=",
    logo18:"https://api-pink-venom.vercel.app/api/logo?url=https://en.ephoto360.com/create-3d-colorful-paint-text-effect-online-801.html&name=",
    logo19:"https://api-pink-venom.vercel.app/api/logo?url=https://en.ephoto360.com/free-online-american-flag-3d-text-effect-generator-725.html&name="
  };

  const textArg = m.body.slice(prefix.length + commandName.length + 1).trim();
  if (!textArg) {
    await conn.sendMessage(msg.from, { text: `⚠️ Please provide text after *${prefix}${commandName}*` }, { quoted: msg });
    return;
  }

  try {
    await conn.sendMessage(msg.from, { react: { text: "⏳", key: msg.key } });

    const requestUrl = logoUrls[commandName] + encodeURIComponent(textArg);
    const res = await axios.get(requestUrl);

    if (res.data?.status && res.data.result?.download_url) {
      await conn.sendMessage(msg.from, {
        image: { url: res.data.result.download_url },
        caption: `✨ Logo generated by ᴘᴏᴘᴋɪᴅ xᴍᴅ\n👤 Requested by: *${senderName}*`,
        contextInfo: {
          externalAdReply: {
            title: "ᴘᴏᴘᴋɪᴅ xᴍᴅ",
            body: senderName,
            thumbnailUrl: "https://files.catbox.moe/kiy0hl.jpg",
            sourceUrl: "https://whatsapp.com/channel/0029VadQrNI8KMqo79BiHr3l",
            mediaType: 1
          }
        }
      }, { quoted: msg });

      await conn.sendMessage(msg.from, { react: { text: "✅", key: msg.key } });
    } else {
      await conn.sendMessage(msg.from, { text: "⚠️ Failed to generate logo. Try again later." }, { quoted: msg });
    }
  } catch (e) {
    console.error(e);
    await conn.sendMessage(msg.from, { text: "⚠️ Error while generating logo. Try again later." }, { quoted: msg });
  }
});
